"""
Use try/except to catch an error, you can try to validate
what happens when we do

my_list = ["a", "b", "c"]
print(my_list[10])
"""


"""
Cause an exception to be raised using the raise keyword and
print a message after you have finished catching the error
at finally.
"""


"""
Use input function to request information to the user and in
the try/except structure catches multiple errors that can be
generated
"""
